#!/bin/bash
echo "Creating assets/.env file..."
cat <<EOF > assets/.env
APP_ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID
APP_ONESIGNAL_API_KEY=$ONESIGNAL_API_KEY
APP_ADMOB_APP_ID=$ADMOB_APP_ID
APP_ADMOB_BANNER_ID=$ADMOB_BANNER_ID
APP_ADMOB_INTERSTITIAL_ID=$ADMOB_INTERSTITIAL_ID
APP_GROQ_API_KEY=$GROQ_API_KEY
APP_PACKAGE_NAME=$PACKAGE_NAME
APP_VERSION_CODE=$VERSION_CODE
APP_VERSION_NAME=$VERSION_NAME
EOF
echo ".env file created."
